name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Authorize to Docker Hub
      run: echo $secrets.REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin
    - name: Build the Docker image
      run: docker build . --tag gedlbauer/my-firstimage:latest
    - name: Tag image with GIT Sha
      run: |
        GIT_SHA="$(git rev-parse --short HEAD)"
        docker tag gedlbauer/my-firstimage:latest gedlbauer/my-firstimage:$GIT_SHA
    - name: Push the Docker image
      run: |
        docker push gedlbauer/my-firstimage:latest
        docker push gedlbauer/my-firstimage:$GIT_SHA
        
